name: daily-report

on:
  schedule:
    - cron: '*/5 * * * *'



jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Update Stats
         run: |
            ./update.sh

        - name: Commit Changes
         run: |
            git commit -am "Daily Commit"
            git push  