name: daily-report

on:
  schedule:
    - cron: '0 0 1 1 1'
  workflow_dispatch:



jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Config Git credentials
          run: |
            git config --global user.email "${{ secrets.EMAIL }}"
            git config --global user.name "${{ secrets.USER_NAME }}"
            git clone https://github.com/harivamsi9/git-greener.git
            


        - name: Update Stats
          run: |
            cd git-greener
            git log --oneline | wc -l
            sudo chmod +x hello.sh
            ./hello.sh > README.md 
            cp ./README.md ../README.md

        - name: Commit Changes
          run: |
            git add README.md
            git commit -am "Daily Commit"
            git push origin main
