name: daily-report

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:



jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Config Git credentials
          run: |
            git config --global user.email "${{ secrets.EMAIL }}"
            git config --global user.name "${{ secrets.USER_NAME }}"


        - name: Update Stats
          run: |
            sudo chmod +x update.sh
            sudo chmod +x hello.sh
            ./update.sh

        - name: Commit Changes
          run: |
            git add README.md
            git commit -am "Daily Commit"
            git push origin main
